### ISSUE TITLE
Example with class

### ISSUE THREAD

**Issue by damianlluch** [benevbright/react-native-toast-banner#22]
Hi,! thanks for sharing.

You have any example with class?

thanks!

**Comment by benevbright** [comment]
```
export const Screen = withToastBannerToggler(MyScreen);
```

You can use `withToastBannerToggler` for your class component. 

You will get `{ showBanner, hideBanner }` as your `prop`.

**Comment by damianlluch** [comment]
Mmm sorry, I'dont understand.

this is my code:

https://pastebin.com/4ZyuhyXj

You give me an example please?

thanks!

**Comment by damianlluch** [comment]
For example, I try use your project when the password and de repeatPassword are diferents

**Comment by benevbright** [comment]
You can wrap your class component like
```
export default connect(MapStateToProps, { login })(withToastBannerToggler(Login));
```
Then use like this in your class
```
this.props.showBanner(
```

**Comment by damianlluch** [comment]
ok.

with parameters?

I tried with this code, but not work


https://pastebin.com/Pe5Ev6Y9

**Comment by benevbright** [comment]
Please check the README and the usage of `showBanner` function. https://github.com/benevbright/react-native-toast-banner#usage
