### ISSUE TITLE
Not visible when bottom sheet is open

### ISSUE THREAD

**Issue by harshinventory** [benevbright/react-native-toast-banner#43]
Hello, 
Is there any way to open the toast banner in particular screen?
And the banner is also not visible when bottom sheet is open.

**Comment by benevbright** [comment]
> the banner is also not visible when bottom sheet is open. 

Hi, 
maybe it's related to the place where you located your `<ToastBannerPresenter />`? Maybe there you can arrange the order with your bottom sheet? 

And what is the bottom sheet exactly? From which library? :) 

> Is there any way to open the toast banner in particular screen?

And I also don't understand this fully but I can tell that this library is a screen agnostic, meaning it's working independently from screens and there is no way to attach it with a screen.
